=== lichaozhy/train/documentation/src/schemas/metadata.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"properties": {
		"title": {
			"type": "string"
		},
		"tags": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"author": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"source": {
			"type": "string"
		},
		"sections": {
			"type": "array",
			"items": {
				"type": "string"
			}
		}
	},
	"required": [
		"title",
		"sections"
	],
	"additionalProperties": false
}

=== lichaozhy/train/documentation/docs/91282732-974d-464c-aac9-f106df0c4da9/metadata.json
{
	"$schema": "../../src/schemas/metadata.json",
	"title": "CGTN：文化传播创新与叙事多元呈现的《遇见—法国篇》",
	"author": [
		"粟韩琬"
	],
	"source": "新媒体与传播学院",
	"tags": [
		"student",
		"internet",
		"internet.master"
	],
	"sections": [
		"1-profile",
		"2-method",
		"3-reflect",
		"4-inspiration",
		"5-conclusion"
	]
}
